### ISSUE TITLE
Fix the slow scrolling effect on the website

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#118]
Visit the URL- https://blackberry.vercel.app/

Try keeping a normal scroll instead of the slow scrolling effect. 

Comment to get assigned

**Comment by SharmaDhruv2511** [comment]
can you please assign me this issue?
as there is no update from saurabh. And i have solved the issue as well. @rohan9024

**Comment by SharmaDhruv2511** [comment]
Hi @rohan9024 any updates?

**Comment by rohan9024** [comment]
@SharmaDhruv2511 go for it

**Comment by SharmaDhruv2511** [comment]
Can you please add the Kwoc and codepeak 2023 tag @rohan9024
