### ISSUE TITLE
Remove Top contributors 

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#119]
Top contributors are not visible. Try looking into the github api through which we are accessing the top contributors

![image](https://github.com/rohan9024/ecommerce/assets/64919642/b2a7381c-04c4-4c75-a2f5-844e8020af83)

**Comment by Afterdie** [comment]
I'd like to work on this issue

**Comment by singhcoder694** [comment]
Hey, @rohan9024 I would like to solve it before solving for customize page issue.. Please assign this to me...

**Comment by singhcoder694** [comment]
@rohan9024 it is working fine, maybe at that time you may have exceeded the API call number

**Comment by singhcoder694** [comment]
<img width="940" alt="Screenshot 2023-12-09 092900" src="https://github.com/rohan9024/ecommerce/assets/114601400/d0fe49b9-467a-4285-ba22-7ea7658ef7ec">
It is already fixed @rohan9024

**Comment by rohan9024** [comment]
Its not working on my end.... idk why

![image](https://github.com/rohan9024/ecommerce/assets/64919642/84e023e3-c178-4235-925d-d7962a319261)

**Comment by Afterdie** [comment]
> Its not working on my end.... idk why
> 
> 
> 
> ![image](https://github.com/rohan9024/ecommerce/assets/64919642/84e023e3-c178-4235-925d-d7962a319261)
> 
> 

you might be getting rate limited by the api

**Comment by rohan9024** [comment]
@Afterdie Is there any way to fix it?

**Comment by singhcoder694** [comment]
Yes there is way if you get the data using authentication you rate limit would increase from (60) to 5000 (not sure). But will definitely increase.

**Comment by singhcoder694** [comment]
@rohan9024 instead of removing it we can increase rate limit wouldn't it be better...

**Comment by rohan9024** [comment]
@singhcoder694 Well, it doesn't suit the theme of the project
