### ISSUE TITLE
feat : add a back to top button.

### ISSUE THREAD

**Issue by NandishM0618** [rohan9024/ecommerce#123]
@rohan9024 please assign this issue to me.

**Comment by rohan9024** [comment]
Please provide a description of where you'll be adding this back button on.

**Comment by NandishM0618** [comment]
the back to top button will be visible after scrolling the main page beyond a certain height.

**Comment by rohan9024** [comment]
Any screenshots to which you're referring to would be appreciated.

**Comment by NandishM0618** [comment]
![issue5](https://github.com/rohan9024/ecommerce/assets/100901899/85c46094-bb6d-4411-87e6-75f4ae68e5e9)

**Comment by singhcoder694** [comment]
Is it completed ? @rohan9024 or if needed to do I can work on this, as it seems an important functionality... for ecommerce websites.

**Comment by rohan9024** [comment]
Closing this because of no response.
