### ISSUE TITLE
Forgot password is placed in center instead on the right

### ISSUE THREAD

**Issue by Afterdie** [rohan9024/ecommerce#127]
![image](https://github.com/rohan9024/ecommerce/assets/82810411/bd066d82-00b5-49c7-bd15-32320b81af0f)

**Comment by DHRUVKHANDELWAL00** [comment]
Hey @rohan9024 , is the issue still opened?.... If yes please assign me

**Comment by rohan9024** [comment]
@DHRUVKHANDELWAL00 go for it and also checkout the earlier conversation on https://github.com/rohan9024/ecommerce/pull/129

**Comment by DHRUVKHANDELWAL00** [comment]
Sure @rohan9024 , also can u label as codepeak?

**Comment by DHRUVKHANDELWAL00** [comment]
![image](https://github.com/rohan9024/ecommerce/assets/99539203/f6e225bb-9649-4a2f-917d-0df24a4e9d74)

**Comment by DHRUVKHANDELWAL00** [comment]
Is it what was needed? @rohan9024

**Comment by rohan9024** [comment]
@DHRUVKHANDELWAL00 we need to place it on the right and not center

**Comment by rohan9024** [comment]
Closing this because of no response.
