### ISSUE TITLE
UI IMPROVMENT : Adding Color Option to the Product Cards And Also Making Corner Rounded 

### ISSUE THREAD

**Issue by Ayusht777** [rohan9024/ecommerce#128]
Hey I want To add A list of color available to this product in the product card also adding box shadow and rounded corner will look's great 
![image](https://github.com/rohan9024/ecommerce/assets/106388215/0d18cc0a-5c1d-418f-8e72-ca3970b35e1f)

**Comment by rohan9024** [comment]
> Hey I want To add A list of color available to this product in the product card also adding box shadow and rounded corner will look's great 
> ![image](https://github.com/rohan9024/ecommerce/assets/106388215/0d18cc0a-5c1d-418f-8e72-ca3970b35e1f)
> 

1. Color options seems interesting. Go ahead 👍
2. If design consistency is considered, rounded corners is mostly not preferred. Sorry.

**Comment by Ayusht777** [comment]
can you add label CODEPEAK

**Comment by Ayusht777** [comment]
hey your all products has 4 colors only so Can I Add the 4 color to data.js
example
` {
    "category": "kids",
    "subCategory": "shirt",
    "title": "Gini and Jony",
    "desc": "Boys Red & Navy Blue Cotton Tartan Checks Hooded Casual Shirt",
    "price": "₹909",
    "imgurl": img19,
    "colors" : ["option1","option2"...]
  },`

or any other way which you recommend

**Comment by rohan9024** [comment]
yeah

**Comment by Ayusht777** [comment]
can you tell me where did you put the styles for Product Cards mean they are render using itemlist but where is the styling for it 
you did not use any map function or anything else can you explain it 
![image](https://github.com/rohan9024/ecommerce/assets/106388215/e553dcdc-36e8-4397-8051-52bad373e58d)

**Comment by rohan9024** [comment]
@Ayusht777 checkout shoeitems.js

**Comment by Ayusht777** [comment]
Hello, here's a preview. If you find it good, I'll proceed to create a pull request.
![image](https://github.com/rohan9024/ecommerce/assets/106388215/796beec6-d358-4214-8699-c833cdafcd2b)

**Comment by rohan9024** [comment]
> Hello, here's a preview. If you find it good, I'll proceed to create a pull request.
> ![image](https://github.com/rohan9024/ecommerce/assets/106388215/796beec6-d358-4214-8699-c833cdafcd2b)
> 

Yeah it looks great🚀
