### ISSUE TITLE
Add styling to the filters

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#130]
![image](https://github.com/rohan9024/ecommerce/assets/64919642/3bb58dd8-02b4-4bae-9477-d1e554f18ebc)

Add some font and styling to the filters and also animations are also appreciated for both filter as well as sort by.

**Comment by singhcoder694** [comment]
@rohan9024 I don't know why in your Repo it is always showing **❌(review required)** while making PR, if you can tell me reason behind this.

**Comment by rohan9024** [comment]
@singhcoder694 actually I have not provided other users to deploy on my end without my review.
