### ISSUE TITLE
Create the animation of the component when hovered on the nav links

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#132]
For reference, Checkout this website and try hovering over nav links.
https://www.nike.com/in/nrc-app

**Comment by tushar-daiya** [comment]
what should be the content when hovered? Like in the reference site they have categories..
and can I work on this?

**Comment by rohan9024** [comment]
@tushar-daiya its completely upto you for deciding the categories. The more categories, the better

**Comment by rohan9024** [comment]
@tushar-daiya any updates? Are you facing any difficulties?

**Comment by tushar-daiya** [comment]
Sorry for the delay. Actually I had an emergency so was not able to do it. I will try making a PR by saturday.
