### ISSUE TITLE
Top to bottom navigation issue

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#134]
1. Checkout https://blackberry.vercel.app/shoes

2. Try clicking on any product.
3. The page starts from the bottom instead it should go from Top to bottom

**Comment by Rithvik9620** [comment]
Hi @rohan9024 ,
           Mostly this issue is caused by the SmoothScroll component. Without that, page is rendering from the top .
Basically, the window.scrollTo(0,0) is not the correct way to scroll to the top when using this smooth-scrollbar dependency as there should be another way to do access it. I could not figure out any other way to access the dom element to scroll to top.

**Comment by rohan9024** [comment]
@Rithvik9620 there might be some issues related to the tailwind config...... assigning you this issue incase you find the solution

**Comment by Rithvik9620** [comment]
@rohan9024 I have solved the issue and as mentioned in CONTRIBUTING.md, I have cloned your project have created a branch and commited my change into it. But when I push, it says access denied. Can you please help me through this as this is new to me.
Thanks.

**Comment by Rithvik9620** [comment]
Should I first fork the project and then clone it to my local or directly clone this project?

**Comment by rohan9024** [comment]
> Should I first fork the project and then clone it to my local or directly clone this project?

1. Yeah, you need to fork this project and after that the copy which is created at your you need to then clone that part.
2. After that follow git clone , etc

**Comment by Rithvik9620** [comment]
@rohan9024 I have raised a PR for this issue. Please review it.

**Comment by rohan9024** [comment]
@Rithvik9620 I think this was medium issue according to me. So I have updated the label accordingly.
