### ISSUE TITLE
On mobile size screen there is overflow of navbar.

### ISSUE THREAD

**Issue by singhcoder694** [rohan9024/ecommerce#135]
<img width="316" alt="Screenshot 2023-12-10 083104" src="https://github.com/rohan9024/ecommerce/assets/114601400/1ffeaef5-4b71-454e-b2fe-bad079bd87ed">
<img width="316" alt="Screenshot 2023-12-10 083113" src="https://github.com/rohan9024/ecommerce/assets/114601400/8a5e980c-0bef-451a-acb7-5b4022e489fa">

I would like to solve this issue under CodePeak'23

**Comment by singhcoder694** [comment]
@rohan9024 I have created a PR but it is showing ❌, can you tell me why it may happen?

**Comment by rohan9024** [comment]
@singhcoder694 Alright it seems great. For bonus 5 points, can you fix the search icon in the search bar 
![image](https://github.com/rohan9024/ecommerce/assets/64919642/872f5098-8f1d-4062-b076-f2239249ef65)

**Comment by singhcoder694** [comment]
Yes

**Comment by singhcoder694** [comment]
Done 
<img width="318" alt="Screenshot 2023-12-11 191304" src="https://github.com/rohan9024/ecommerce/assets/114601400/8ce06b9a-8a7d-4247-bfb9-9043dcd06259">
