### ISSUE TITLE
Validating Error and Displaying Error message to user in  registration form .

### ISSUE THREAD

**Issue by HarshitSharma4** [rohan9024/ecommerce#138]
The problem is that after clicking on the register button,  registration form does not display any error messages, making it difficult for users to identify and correct input errors.

[Screencast from 2023-12-10 17-27-53.webm](https://github.com/rohan9024/ecommerce/assets/106171546/618ba100-e33f-4828-aa2e-d18893ee084f)

**Comment by TamLeCNTT** [comment]
Can I work on this issue?

**Comment by cangdt** [comment]
Can I work on this issue?

**Comment by HarshitSharma4** [comment]
I have write this issue for myself.

**Comment by rohan9024** [comment]
@HarshitSharma4 go for it!

**Comment by rohan9024** [comment]
@cangdt meanwhile you can work on existing issues or create a new issue

**Comment by HarshitSharma4** [comment]
can you add label  codepeak

**Comment by Yash-Ainapure** [comment]
@HarshitSharma4  are you working on it?? @rohan9024   Otherwise you can assign it to me.

**Comment by rohan9024** [comment]
> @HarshitSharma4  are you working on it?? @rohan9024   Otherwise you can assign it to me. 

Go for it.

**Comment by Yash-Ainapure** [comment]
sorry for late , I will surely make a PR till morning.
