### ISSUE TITLE
Font and Description of Women's section

### ISSUE THREAD

**Issue by AishwaryaIGDTUW** [rohan9024/ecommerce#144]
The font and description of women section is a bit lame and more like a sentence which is not catchy for an 
E-Commerce website . Thus i would like to change the font and also make the description sounds short and nice.

Please assign me this issue @rohan9024 

![picture](https://github.com/rohan9024/ecommerce/assets/122673457/7c22031f-fd87-425b-93ef-b4636c1ff0b5)

**Comment by rohan9024** [comment]
Are you working on this? If not then let me close this issue.
