### ISSUE TITLE
Signup and login is not working, An authentication system in needed for login and signup

### ISSUE THREAD

**Issue by maheshwar-verma** [rohan9024/ecommerce#148]

**Comment by Albert-2** [comment]
hey @rohan9024
I would very much like to work on this issue
please assign me the same under codepeak'23
Thank you for considering....! :)

**Comment by maheshwar-verma** [comment]
@Albert-2 i created this issue for myself to solve 🙂

**Comment by rohan9024** [comment]
@maheshwar-verma @Albert-2 This was already created last year which I had to remove so I don't think we need to proceed with this. Can you guys create a new feature instead? I'm happy to assign you guys differently.

Thanks @maheshwar-verma for taking an initiative😄
