### ISSUE TITLE
Wishlist page is not there

### ISSUE THREAD

**Issue by PSS2134** [rohan9024/ecommerce#158]

**Comment by PSS2134** [comment]
Since Cart Page is there , I have added a wishlisht page where products can be added to wishlish after clicking on heart icon. I have created PR #160 @rohan9024

**Comment by PSS2134** [comment]
![Screenshot 2023-12-22 091802](https://github.com/rohan9024/ecommerce/assets/101321904/c24afd35-2dd4-4e50-bd69-4a7024acd022)

**Comment by PSS2134** [comment]
@rohan9024 I have created a PR #162  with all updated functionalities, description and video illustrations

**Comment by PSS2134** [comment]
and Are there any other issues I could work upon like authentication part @rohan9024

**Comment by rohan9024** [comment]
@PSS2134 You can work on the existing issues if the issue has been stale and also if you can create new features😄

Would love to look for new features on ecommerce
