### ISSUE TITLE
navItems are not visible in mid-sized screen

### ISSUE THREAD

**Issue by maheshwar-verma** [rohan9024/ecommerce#165]
![Screenshot 2023-12-22 204621](https://github.com/rohan9024/ecommerce/assets/115862713/a17ed85b-4fa1-4bd1-899e-7cfe17a04df0)

**Comment by maheshwar-verma** [comment]
https://github.com/rohan9024/ecommerce/assets/115862713/c7538f55-730c-4855-bd41-3e3ccb26b87d

this was the problem. the navitems are visible in smaller screens but in mid-sized screens eg. tablet , they are not visible.
i created a pull request fixing this

**Comment by rohan9024** [comment]
@maheshwar-verma Alright, Great work! Also, I would like to suggest that whenever you create a PR, mention the issue no. which you are solving. It becomes easier for the maintainer to respond faster


Btw appreciate your efforts and enthusiasm to this project😄
