### ISSUE TITLE
Payment Gateway Integration + Order Placed Successfully Page

### ISSUE THREAD

**Issue by PSS2134** [rohan9024/ecommerce#166]
1. Implement a Payment Gateway which takes to doing payment ( not really ) and after payment confirmation
2. Order Placed Successfully Page
@rohan9024

**Comment by PSS2134** [comment]
@rohan9024

**Comment by rohan9024** [comment]
@PSS2134 which payment gateway are you going to use?

**Comment by PSS2134** [comment]
Razorpay? @rohan9024

**Comment by rohan9024** [comment]
We had a payment gateway before this. 
Currently not looking for it now. Let's focus on the other issues which you have created now.

**Comment by PSS2134** [comment]
I was just thinking of moving forward from cart section to place order successfully , so that then we can go on to make a user profile with details and order history and tracking of order through order id? @rohan9024
