### ISSUE TITLE
Add favicon and change title

### ISSUE THREAD

**Issue by Dibyendu303** [rohan9024/ecommerce#17]
Hey, I noticed that the website does not have a favicon and the title is "React App". Can I work on it ?

**Comment by rohan9024** [comment]
@Dibyendu303 go for it

**Comment by rohan9024** [comment]
@Dibyendu303 have you done it ?
please attach ss if you have done so

**Comment by Dibyendu303** [comment]
@rohan9024 Submitted a PR #19
