### ISSUE TITLE
404 page missing

### ISSUE THREAD

**Issue by Yash-Ainapure** [rohan9024/ecommerce#171]
I would like to add a "404 page not found" page . If the redirect url is not present then this page will be shown instead of showing errors on page which is not good for user experience
@rohan9024 
the page i am talking about will look like this :

![Screenshot (127)](https://github.com/rohan9024/ecommerce/assets/136250383/8a36cb4e-d22f-4946-a13d-c45fccf0b61b)

**Comment by rohan9024** [comment]
@Yash-Ainapure go ahead👍
