### ISSUE TITLE
proper responsivness for cart and wishlist page

### ISSUE THREAD

**Issue by maheshwar-verma** [rohan9024/ecommerce#178]
https://github.com/rohan9024/ecommerce/assets/115862713/316f7708-8b7d-4e48-aaef-74ff14c9ee3c

![Screenshot 2023-12-26 200352](https://github.com/rohan9024/ecommerce/assets/115862713/4041ef46-31ff-4e36-b56d-1d4bdd196ce2)
cart and wishlist page are not responsive for mobile screens

**Comment by rohan9024** [comment]
@maheshwar-verma please get assigned first and only after that create a pull request.

**Comment by maheshwar-verma** [comment]
okay, but i created a pr for previous issue already

**Comment by rohan9024** [comment]
But unless you get that merged, you can't move with the other issues.

**Comment by maheshwar-verma** [comment]
Okay I got it.
