### ISSUE TITLE
bad Footer Ui

### ISSUE THREAD

**Issue by siwamsingh** [rohan9024/ecommerce#182]
The current footer of the website has a lot of room for improvement . the current design donot align properly .
<img width="236" alt="bb" src="https://github.com/rohan9024/ecommerce/assets/140843501/cd81638c-66c9-46db-a982-147181a62b97">

**Comment by rohan9024** [comment]
@aindree-2005

**Comment by siwamsingh** [comment]
@rohan9024 I would to work on this issue can you assign this to me

**Comment by rohan9024** [comment]
> @rohan9024 I would to work on this issue can you assign this to me
> 

The codepeak event has been wrapped up and we're not accepting any PRs
