### ISSUE TITLE
Add animations to any component on home page

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#2]

**Comment by SattyamSamania** [comment]
Hey @rohan9024 I would like to work on this issue pls tell me further what to do next.

**Comment by rohan9024** [comment]
@SattyamSamania one at a time ....you have already been assigned an issue

**Comment by SattyamSamania** [comment]
> @SattyamSamania one at a time ....you have already been assigned an issue

I understand. No worries, you can assign to anyone else.

**Comment by iamatifmoin** [comment]
@rohan9024 
Can you provide some description of the issue please?

**Comment by rohan9024** [comment]
@iamatifmoin try using framer motion and implement any animations on the components ........ also lemme know you're working on it

**Comment by devika-singh** [comment]
@rohan9024 can two people work on this issue?

**Comment by iamatifmoin** [comment]
> @iamatifmoin try using framer motion and implement any animations on the components ........ also lemme know you're working on it

Yes I am working on it.

**Comment by rohan9024** [comment]
@devika-singh ask @iamatifmoin if he's comfortable with it

**Comment by rohan9024** [comment]
@devika-singh if not you can create issues and try solving it as well

**Comment by iamatifmoin** [comment]
@devika-singh 
if I cannot resolve the issue today, you take it up.

**Comment by rohan9024** [comment]
@iamatifmoin any updates?

**Comment by iamatifmoin** [comment]
@rohan9024 
You can assign it to someone else.

**Comment by rohan9024** [comment]
@devika-singh you wanna get assigned?

**Comment by nik132-eng** [comment]
can I take this issue, if this is unresolved ?

**Comment by devika-singh** [comment]
@rohan9024 I made a pull request for this issue pls check it https://github.com/rohan9024/ecommerce/pull/53
