### ISSUE TITLE
Create a responsive Navbar with Hamburger menu

### ISSUE THREAD

**Issue by Dibyendu303** [rohan9024/ecommerce#20]
The navbar is not responsive. I want to create a responsive Navbar with Hamburger menu. Can I work on it ? @rohan9024

**Comment by rohan9024** [comment]
@Dibyendu303 go for it

**Comment by Dibyendu303** [comment]
@rohan9024 this issue is 20 points in other projects. Please make it 20 points.

**Comment by rohan9024** [comment]
@Dibyendu303 once your code is merged then you will be given 20 points
