### ISSUE TITLE
Add margin top and margin bottom 

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#23]
![image](https://user-images.githubusercontent.com/64919642/206837704-4f04541d-cf3c-42b6-a7a2-dc37e30c3218.png)

![image](https://user-images.githubusercontent.com/64919642/206837723-a3420e9c-dc07-42a1-adf1-afc799dfba24.png)

**Comment by kshitij01042002** [comment]
Where exactly do you want margin? Can you elaborate more?

**Comment by rohan9024** [comment]
@kshitij01042002 this has been solved ,....closing this issue
