### ISSUE TITLE
Implement sign up page after clicking on join us

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#24]
![image](https://user-images.githubusercontent.com/64919642/206837955-c5d7cd16-26c1-41c4-829b-bc3e0cff00dd.png)

**Comment by Dibyendu303** [comment]
Please assign this to me @rohan9024

**Comment by rohan9024** [comment]
@Dibyendu303 go for it..... keep the same design; add more fields like name, phone no., etc
