### ISSUE TITLE
Add to cart functionality

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#3]

**Comment by itz-deepak** [comment]
I would like to contribute into this project
Please assign this to me

**Comment by rohan9024** [comment]
@itz-deepak you working on it? what about ur previous task?

**Comment by rohan9024** [comment]
@itz-deepak alright be quick

**Comment by rohan9024** [comment]
@itz-deepak any updates?

**Comment by Dibyendu303** [comment]
Please assign this to me @rohan9024

**Comment by maddy020** [comment]
Please assign this issue to me 
I have already resolved and just going to merge it

**Comment by rohan9024** [comment]
@maddy020 can you please record a video and show

**Comment by maddy020** [comment]
Sending you in a minute

**Comment by maddy020** [comment]
https://user-images.githubusercontent.com/103564105/206895352-2798b646-1022-481e-b520-96b98c2b3a03.mp4

**Comment by rohan9024** [comment]
> 
> https://user-images.githubusercontent.com/103564105/206895352-2798b646-1022-481e-b520-96b98c2b3a03.mp4
> 
> 

@maddy020 hey, sorry for late reply! Great work🎉 
Can we have the products displayed after clicking on cart option?

Likewise you'll get extra points for that

**Comment by maddy020** [comment]
For that feature I have to add new  page and add items through mapping 
I think for that please create a new issue and assign that to me
For the above issue I have changed a lot of files, and adding this will create a messy code to contribute
What is your suggestion over it?

**Comment by maddy020** [comment]
Final Changes
https://user-images.githubusercontent.com/103564105/207936166-a6aea163-f16e-44d8-8706-0381127ccaaf.mp4

**Comment by Dibyendu303** [comment]
@rohan9024 . I can create the cart page.

**Comment by maddy020** [comment]
I can also do that but I am asking to create a new issue for it so that I can contribute in effective way

**Comment by maddy020** [comment]
I have started making cart page

**Comment by rohan9024** [comment]
@maddy020 alright! Ask if you have any doubts

**Comment by maddy020** [comment]
Hi @rohan9024 where can I ask my doubts

**Comment by Dibyendu303** [comment]
@rohan9024 Please assign me this

**Comment by rohan9024** [comment]
@Dibyendu303 go for it
