### ISSUE TITLE
Navbar showing twice

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#33]
![image](https://user-images.githubusercontent.com/64919642/206865180-0847aa0f-ec7a-48cc-b706-2edde28b0b36.png)

**Comment by kshitij01042002** [comment]
Assign me this issue.

**Comment by rohan9024** [comment]
@kshitij01042002 go for it

**Comment by kshitij01042002** [comment]
But when I am building the project it's isn't showing twice

**Comment by rohan9024** [comment]
@kshitij01042002 click on shoes section

**Comment by rohan9024** [comment]
Someone has fixed the navbar, but the footer is rendered twice so you can fix that for now

**Comment by kshitij01042002** [comment]
> Someone has fixed the navbar, but the footer is rendered twice so you can fix that for now

Yeahhh, same thing
