### ISSUE TITLE
Add more categories like kids, men, women

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#4]

**Comment by itz-deepak** [comment]
Please assign this issue to me @rohan9024

**Comment by rohan9024** [comment]
@itz-deepak any updates?

**Comment by itz-deepak** [comment]
please elaborate the issue
Does it mean this

![image](https://user-images.githubusercontent.com/83635276/206500733-58a1a334-2aee-435f-8882-f93242725613.png)

**Comment by rohan9024** [comment]
@itz-deepak make a different route like for example consider

 MEN- 

1. Create a different route 
2. List different tshirts, pants, etc 
3. Every tshirt has a fav icon, add to cart, price ,discounted price just like other ecommerce platforms.

Same for other categories as well like kids women

**Comment by rohan9024** [comment]
Don't add groceries and all in the navlinks ..... Make a different route for existing navlinks

**Comment by kshitij01042002** [comment]
Assign me this, I can work on it

**Comment by rohan9024** [comment]
@kshitij01042002 go for it

**Comment by kshitij01042002** [comment]
@rohan9024 You want to segregate things right? Kind of like a filter?
Like in men if I click on tshirts it should list all the tshirts? likewise?

**Comment by rohan9024** [comment]
@kshitij01042002 yeah go for it

**Comment by kshitij01042002** [comment]
I can try my best!

**Comment by kshitij01042002** [comment]
@rohan9024 it's difficult for me to add more categories. if you want you can assign this issue to anyone else

**Comment by kshitij01042002** [comment]
I am not able to find the data to add more products

**Comment by rohan9024** [comment]
@kshitij01042002 alright np
