### ISSUE TITLE
Add parallex animation on homepage

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#49]
Refer this blog if you're a beginner-->

https://blog.devgenius.io/parallax-effect-in-reactjs-b304fd5f9a67

**Comment by pundarikaksha7** [comment]
Kindly assign

**Comment by rohan9024** [comment]
@pundarikaksha7 go for it

**Comment by rohan9024** [comment]
@pundarikaksha7 any updates?

**Comment by pundarikaksha7** [comment]
Not any yet, a bit busy right now, you can reassign if you want

**Comment by Tushar98644** [comment]
if the issue still persists, assign me .....

**Comment by rohan9024** [comment]
@Tushar98644 go for it

**Comment by rohan9024** [comment]
@Tushar98644 are you working on it?

**Comment by Tushar98644** [comment]
I am actually facing an error....could you help me with that?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tushar98644** [comment]
> @Tushar98644 are you working on it?

yup but facing an error on setting up the environment....can you help me with that?

**Comment by Tushar98644** [comment]
<img width="1440" alt="Screenshot 2022-12-13 at 1 46 54 PM" src="https://user-images.githubusercontent.com/107763774/207363369-d0048e46-ae95-4141-bd8e-5409f0d34542.png">
i am getting a blank page on starting the server ....

**Comment by Dibyendu303** [comment]
@Tushar98644 . You need to generate your own Firebase API keys. Refer to the [ENVinstructions.md](../blob/main/ENVinstructions.md) file

**Comment by Tushar98644** [comment]
> @Tushar98644 . You need to generate your own Firebase API keys. Refer to the [ENVinstructions.md](../blob/main/ENVinstructions.md) file

ok thnx .....i will check it out .....

**Comment by rohan9024** [comment]
> > @Tushar98644 . You need to generate your own Firebase API keys. Refer to the [ENVinstructions.md](../blob/main/ENVinstructions.md) file
> 
> ok thnx .....i will check it out .....

@Tushar98644 any updates? Or are you stuck somewhere?

**Comment by Tushar98644** [comment]
> > > @Tushar98644 . You need to generate your own Firebase API keys. Refer to the [ENVinstructions.md](../blob/main/ENVinstructions.md) file
> > 
> > 
> > ok thnx .....i will check it out .....
> 
> @Tushar98644 any updates? Or are you stuck somewhere?

will complete asap...have my hands full on something now....

**Comment by rohan9024** [comment]
@Tushar98644 are you working on it?

**Comment by Tushar98644** [comment]
> @Tushar98644 are you working on it?

have the dependencies been fixed ?

**Comment by rohan9024** [comment]
@Tushar98644 yes, now you can work on it

**Comment by rohan9024** [comment]
@Tushar98644 any updates?

**Comment by rohan9024** [comment]
@kshitij01042002 you wanna work on this?

**Comment by Dibyendu303** [comment]
@rohan9024 . I have created one parllax animation. Check here: [Parallax animation](https://codesandbox.io/s/react-scroll-parallax-hero-banner-forked-tui6tc?file=/src/AdvancedBanner.tsx)

**Comment by rohan9024** [comment]
@Dibyendu303 alright go for it
