### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by kshitij01042002** [rohan9024/ecommerce#57]
Since all the data is rendered from hard-coded Json file. We should use firebase firestore to store all the data and thus render
it accordingly. This task can be divided into following tasks

1. Creating database schema to store all the data and creating Storage bucket to store the images.
2. Rendering all the data from database

I think this task should be done in two different PR.

**Comment by rohan9024** [comment]
@kshitij01042002 @Dibyendu303  has implemented firebase login/ logout maybe he can guide on it
