### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by kshitij01042002** [rohan9024/ecommerce#58]
Since the data currently in the website is all hardcoded, it's not a good practise we should make a page for admin to upload product details which is then rendered rather than hard coded data

Current Json Data format
{
        "category": "Women",
        "title": "Antheaa",
        "desc": "Black & Rust Orange Floral Print Tiered Midi Fit & Flare Dress with Ruffles",
        "price": "₹983",
        "img":img35
 }

We can take these inputs from the admin along with this one additional information of sub-category will be useful.

**Comment by rohan9024** [comment]
@kshitij01042002 go for it

**Comment by kshitij01042002** [comment]
@rohan9024 before working on this issue I think issue #57 should be done first.
Soo if you can assign me that first
