### ISSUE TITLE
Make CONTRIBUTED BY page 

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#64]

**Comment by Dibyendu303** [comment]
Please assign me @rohan9024

**Comment by rohan9024** [comment]
> Please assign me @rohan9024 

List all the contributors who have contributed to this page.
Try making it look more attractive (extra points)

**Comment by Dibyendu303** [comment]
@rohan9024 should I create a new page or should I list the contributors in the readme page itself ?

**Comment by rohan9024** [comment]
> @rohan9024 should I create a new page or should I list the contributors in the readme page itself ?

Make a new route called contributors and list all the contributors

**Comment by rohan9024** [comment]
> @rohan9024 should I create a new page or should I list the contributors in the readme page itself ?

And also in the readme section

**Comment by Dibyendu303** [comment]
Okay
