### ISSUE TITLE
Fix the shoes section

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#65]
![image](https://user-images.githubusercontent.com/64919642/207904641-466d6021-12d8-46c2-ae92-5d3cde6047bd.png)

**Comment by kshitij01042002** [comment]
@rohan9024 this issue isn't on my side I guess some one must one messed up with css

**Comment by rohan9024** [comment]
@kshitij01042002 visit this link-->

http://donation-box-1fin.vercel.app/

**Comment by kshitij01042002** [comment]
Got you! assign me this

**Comment by kshitij01042002** [comment]
I'll fix this too along with adding the admin page

**Comment by rohan9024** [comment]
@kshitij01042002 make separate PRs

**Comment by kshitij01042002** [comment]
Okay

**Comment by rohan9024** [comment]
@kshitij01042002 please make a different PR for this

**Comment by kshitij01042002** [comment]
@rohan9024 I don't know how can I do this cause I have commited changes to the PR raised, it's fine if I don't get points for this one because it wasn't much of a task
