### ISSUE TITLE
Implement smooth scrolling for all pages

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#67]

**Comment by codeboyfriend** [comment]
can i work on this?

**Comment by rohan9024** [comment]
> can i work on this?

@codeboyfriend go for it

**Comment by rohan9024** [comment]
@codeboyfriend any updates?

**Comment by kshitij01042002** [comment]
@rohan9024 can you explain a little more about what exactly are you expecting?

**Comment by Prasad-mutnale** [comment]
@rohan9024 can you assign me this issue?, 
 i can solve this issue!!

**Comment by rohan9024** [comment]
@kshitij01042002 sorry for the late reply 
Refer this video -->

Implement only the scrolling part
https://youtu.be/QzW03hyw_bU

**Comment by Prasad-mutnale** [comment]
> @Prasad-mutnale Refer this video -->
> 
> Implement only the scrolling part https://youtu.be/QzW03hyw_bU

Okay,
Thank you @rohan9024
