### ISSUE TITLE
Make a new admin dashboard

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#71]

**Comment by kshitij01042002** [comment]
What all things do you need in the admin dashboard? @rohan9024

**Comment by rohan9024** [comment]
@kshitij01042002 Dashboard like this -->

https://dribbble.com/shots/18439419-Admin-dashboard-analytics-UX

Implement this design you'll get 50 points. Also make it dynamic

**Comment by kshitij01042002** [comment]
What metrics do you want to see in dashboard?

**Comment by rohan9024** [comment]
@kshitij01042002 yeah sure. Looks cool just stick to the UI I have provided

**Comment by kshitij01042002** [comment]
@rohan9024 actually due to an emergency I have to go out of station and won't be back till 6th of January, you can assign this issue to someone else.
Apologies.

**Comment by singhcoder694** [comment]
@rohan9024 what work in needed to be done except making that UI. That page has most of the things which are not applicable for this website as of now. We can only show number of items dynamically , sales etc can be made like this but they can't be dynamic as of now.

**Comment by rohan9024** [comment]
@singhcoder694 I don't think for now we need this..... Look for existing issues or create a new one
