### ISSUE TITLE
Deletion of a product from the admin panel

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#72]
Please attach a video after you have implemented [also show the deletion from the database as well]

**Comment by GauravGupta993** [comment]
Hi @rohan9024, I would like to work on this issue. Please assign this issue to me.

**Comment by singhcoder694** [comment]
Where is admin panel on website do you mean on respective pages there is need to enable delete option for product
@rohan9024

**Comment by rohan9024** [comment]
@singhcoder694 We don't need an admin panel for now
