### ISSUE TITLE
Display leaderboard of github users 

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#73]
Please attach a video after you have implemented

**Comment by Dibyendu303** [comment]
Which github users do you want to display ?

**Comment by rohan9024** [comment]
> Which github users do you want to display ?

@Dibyendu303 the people who have contributed to this repository

**Comment by Dibyendu303** [comment]
@rohan9024  That is already available in the Contributors page. Only the points system is missing.

**Comment by MCoder86A** [comment]
Shall I make it? I will be using github public api to fetch realtime contribution data of these repo.
