### ISSUE TITLE
Fix the close button [styling wise]

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#75]
![image](https://user-images.githubusercontent.com/64919642/208233325-93dec460-5b61-42ce-8934-5d23bce8c347.png)

**Comment by iamatifmoin** [comment]
@rohan9024 
Please assign me this issue.

**Comment by Prasad-mutnale** [comment]
Please assign me this issue i can figure it out 

Please assign me

**Comment by Prasad-mutnale** [comment]
> @Prasad-mutnale all right, all the best

Thank you

**Comment by Prasad-mutnale** [comment]
@rohan9024 Please close this issue
