### ISSUE TITLE
Add multiple sections in sidebar like shirts, tshirts, pants, bags for men

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#78]
Refer these website -->

https://www.nike.com/in/w/womens-bags-backpacks-5e1x6z9xy71

https://www.adidas.co.in/bags?cm_mmc=AdieSEM_Google_Search-_-AlwaysON-_--_--_-dv%3AeCom-_-cn%3AAlwaysON-_-pc%3AGoogle_Search&cm_mmc=AdieSEM_Google-_-%7BCampaignName%7D-_-%7BAdgroupName%7D-_-adidas%20bags&cm_mmc1=IN&cm_mmc2=adidas-Brand_Expanded-B-Phrase-Accessories-Multiple----IN--eCom-Paid_Search&cm_mmca1=IN&cm_mmca2=p

**Comment by kshitij01042002** [comment]
We can add multiple sections in sidebar.like shirts, tshirts, pants, bags. 
While making database schema I have added option for subcategory this could help us get through.
Assign me this.

**Comment by Dibyendu303** [comment]
Please assign me @rohan9024

**Comment by rohan9024** [comment]
@kshitij01042002 for now you can just make the changes as per the issue I have specified ......later on you can get assigned with issue you created.

**Comment by rohan9024** [comment]
@Dibyendu303 pick a different issue [also you have been assigned an issue already
]

**Comment by kshitij01042002** [comment]
> @kshitij01042002 for now you can just make the changes as per the issue I have specified ......later on you can get assigned with issue you created.

We can add multiple sections in sidebar.like shirts, tshirts, pants, bags.

should I go with solution?

**Comment by rohan9024** [comment]
@kshitij01042002 alright go for it

**Comment by kshitij01042002** [comment]
> @kshitij01042002 alright go for it.... do this only for men for now

@rohan9024 men or women?

**Comment by kshitij01042002** [comment]
Okay! working on it.
