### ISSUE TITLE
Add sub-category section in Mens section

### ISSUE THREAD

**Issue by kshitij01042002** [rohan9024/ecommerce#79]
We can add sub-category section in Mens section like shirt,T-shirt,pant,etc

**Comment by kshitij01042002** [comment]
@rohan9024 can you assign me these issues?

**Comment by kshitij01042002** [comment]
@rohan9024 can we connect on discord?

**Comment by rohan9024** [comment]
@kshitij01042002 I'm actually travelling rn... what's the problem?

**Comment by kshitij01042002** [comment]
@rohan9024 just some points issue, so whenever possible just checkout the discord channel

**Comment by kshitij01042002** [comment]
@rohan9024 
I haven't reeived points for issues #78 
#79
#80 
#82 

and for PR
#63  (You have labelled it but I didn't receive the points)

and for solving issue
#59 

can you please look into this?

**Comment by rohan9024** [comment]
@kshitij01042002 you won't get those points because those were raised by me and then was subdivided by you in other issues you raised

**Comment by rohan9024** [comment]
@kshitij01042002 the rule says that the idea should be yours when you raise an issue ........not an issue which already exists

**Comment by rohan9024** [comment]
@kshitij01042002 for #63 I have informed the maintainers they'll look into it

And for #59 you have been awarded points for raising issue 5 points and raising PR in #69

**Comment by kshitij01042002** [comment]
> @kshitij01042002 for #63 I have informed the maintainers they'll look into it
> 
> And for #59 you have been awarded points for raising issue 5 points and raising PR in #69

Okay! Got it!
#59 have the same problem you have labelled it but I didn't receive the points.
And sorry for all the inconvenience caused due to all this..
Also thanks for understanding

**Comment by rohan9024** [comment]
@kshitij01042002 you talking about the issue right ?
lemme inform the maintainer

**Comment by kshitij01042002** [comment]
> @kshitij01042002 you talking about the issue right ? lemme inform the maintainer

Yeah you have labelled 
Issue #59 
and PR #69 , but I haven't received points
