### ISSUE TITLE
Add login page

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#8]

**Comment by SattyamSamania** [comment]
Hey @rohan9024 can I work on this issue. Also tell me further what's the approach.

**Comment by rohan9024** [comment]
Add email password buttons use the states for that and also user should be able to login

**Comment by SattyamSamania** [comment]
> Add email password buttons use the states for that and also user should be able to login

Which tech stack or technology should I use to build that?

**Comment by rohan9024** [comment]
Read the contributing.md file

**Comment by SattyamSamania** [comment]
@rohan9024 okay i will create using react

**Comment by pradeepkumar11519** [comment]
Hey @rohan9024 can i work on this issue as i already know react js and can i use react query along with next js??

**Comment by rohan9024** [comment]
@pradeepkumar11519 ask @SattyamSamania . If he's fine with it.

**Comment by pradeepkumar11519** [comment]
@sattyamsamania is it fine with u if i can join and make a login page??

**Comment by pradeepkumar11519** [comment]
can i use other react tools like react query and react formik??

**Comment by rohan9024** [comment]
@SattyamSamania  @pradeepkumar11519 yeah sure

**Comment by rohan9024** [comment]
@SattyamSamania @pradeepkumar11519 are you guys working on it?

because login  page already exists ......try adding state and session ........the user should be able to login and maintain the session 

for extra points implement authentication

**Comment by SattyamSamania** [comment]
> @SattyamSamania @pradeepkumar11519 are you guys working on it?
> 
> because login page already exists ......try adding state and session ........the user should be able to login and maintain the session
> 
> for extra points implement authentication

Okay

**Comment by pradeepkumar11519** [comment]
can i use next js as using next js can help me store the authentication token in http secure cookie??

**Comment by pradeepkumar11519** [comment]
can i use my own database to store user details for login and signup??

**Comment by rohan9024** [comment]
@SattyamSamania @pradeepkumar11519 what's the update guys? You're taking too long.... the login page already exists ...you need to just add session storage and cookies w/o using database

**Comment by SattyamSamania** [comment]
> @SattyamSamania @pradeepkumar11519 what's the update guys? You're taking too long.... the login page already exists ...you need to just add session storage and cookies w/o using database

Can I make PR tomorrow? After that you can assign to anyone else

**Comment by rohan9024** [comment]
@SattyamSamania yeah sure but show me what's the progress?

**Comment by SattyamSamania** [comment]
> @SattyamSamania yeah sure but show me what's the progress?

I am learning react now

**Comment by rohan9024** [comment]
@pradeepkumar11519 what about you?

**Comment by rohan9024** [comment]
@SattyamSamania pradeep is working with you right ?
lemme know so that only you will get assigned

**Comment by SattyamSamania** [comment]
> @SattyamSamania pradeep is working with you right ? lemme know so that only you will get assigned

Don't Know.

**Comment by rohan9024** [comment]
pradeep unassigned

**Comment by SattyamSamania** [comment]
> @SattyamSamania what's the update?

Not started yet. Can you provide some resources to solve this problem?

**Comment by rohan9024** [comment]
@SattyamSamania https://youtu.be/lhMKvyLRWo0
