### ISSUE TITLE
Add more sub-sections in Shoes

### ISSUE THREAD

**Issue by kshitij01042002** [rohan9024/ecommerce#80]
Just like bag section as mentioned in issue #78 , we can add section here like sports, casuals, formals,etc

**Comment by kshitij01042002** [comment]
@rohan9024 can you assign me this issue?

**Comment by kshitij01042002** [comment]
@rohan9024 this issue is not yet completed

**Comment by Dibyendu303** [comment]
@kshitij01042002 please close this issue since it is completed
