### ISSUE TITLE
Add more sub-sections in Kids

### ISSUE THREAD

**Issue by kshitij01042002** [rohan9024/ecommerce#82]
Add more sub-sections in Kids like shirt,pants,frocks

**Comment by Prasad-mutnale** [comment]
Can you assign me this i can solve it please assign me

**Comment by rohan9024** [comment]
> Can you assign me this i can solve it please assign me 

@Prasad-mutnale ask @kshitij01042002 if he's okay with it

**Comment by rohan9024** [comment]
@Prasad-mutnale you can look for other issues as well

**Comment by rohan9024** [comment]
@kshitij01042002 can you take prasad with you so that even he'll learn something from this? it's all upto you.....
I can assign both of you [both will get same 10/20 points]

**Comment by kshitij01042002** [comment]
@rohan9024  Works for me, @Prasad-mutnale if he wants to work along with me.

**Comment by rohan9024** [comment]
> @rohan9024  Works for me, @Prasad-mutnale if he wants to work along with me.

@Prasad-mutnale you fine with it?

**Comment by Prasad-mutnale** [comment]
> > @rohan9024  Works for me, @Prasad-mutnale if he wants to work along with me.
> 
> @Prasad-mutnale you fine with it?

yeah i'm fine

**Comment by kshitij01042002** [comment]
> > > @rohan9024  Works for me, @Prasad-mutnale if he wants to work along with me.
> > 
> > 
> > @Prasad-mutnale you fine with it?
> 
> yeah i'm fine

@Prasad-mutnale you got discord? or anything else soo we can communicate better rather than spamming the comment section of the issue?

**Comment by Prasad-mutnale** [comment]
> > > > @rohan9024  Works for me, @Prasad-mutnale if he wants to work along with me.
> > > 
> > > 
> > > @Prasad-mutnale you fine with it?
> > 
> > 
> > yeah i'm fine
> 
> @Prasad-mutnale you got discord? or anything else soo we can communicate better rather than spamming the comment section of the issue?

yeah in discord we can communicate

**Comment by kshitij01042002** [comment]
Then join the ecommerce channel and we can start working!!

**Comment by Prasad-mutnale** [comment]
> Then join the ecommerce channel and we can start working!!

yeah sure

**Comment by Prasad-mutnale** [comment]
hello @rohan9024 i'm not available for next 2 days because i have exam for that reason i couldn't  solve this issue 
@kshitij01042002 will do PR
