### ISSUE TITLE
add the search suggestions to be showin below the search box instead of rendring on the screen

### ISSUE THREAD

**Issue by Prasad-mutnale** [rohan9024/ecommerce#91]
![image](https://user-images.githubusercontent.com/81313711/208975540-9927b0f1-b323-410f-a94f-53ea740e6c21.png)

**Comment by ozair-dev** [comment]
I may work on this issue in my free time

**Comment by Prasad-mutnale** [comment]
> I may work on this issue in my free time

@ozair-dev ask @rohan9024 he will assign you

**Comment by rohan9024** [comment]
@Prasad-mutnale go for it

**Comment by rohan9024** [comment]
> I may work on this issue in my free time

you can pick another issue

**Comment by Prasad-mutnale** [comment]
> @Prasad-mutnale go for it

yeah sure

**Comment by rohan9024** [comment]
@Prasad-mutnale any updates?

**Comment by Prasad-mutnale** [comment]
> @Prasad-mutnale any updates?

i'm working on it!! soon i will do PR
